branch-defaults:
  trunk:
    environment: mystore-api-dev
environment-defaults:
  mystore-api-dev:
    branch: null
    repository: null
global:
  application_name: mystore-api
  default_ec2_keyname: id_rsa
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
